//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expansion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expansion()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ExpansionId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Icon { get; set; }
        public Nullable<System.DateTime> WorkerEditTime { get; set; }
        public int GameId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual Game Game { get; set; }
    }
}
