//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyValueTableModel
    {
        public int KeyValueTableModelId { get; set; }
        public string Title { get; set; }
        public string Direction { get; set; }
        public string Name { get; set; }
    
        public virtual KeyValueModels KeyValueModels { get; set; }
    }
}
