//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyValueModels
    {
        public int KeyValueModelsId { get; set; }
        public string Label { get; set; }
        public string Key { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public int KeyValueTableModelId { get; set; }
    
        public virtual KeyValueTableModel KeyValueTableModel { get; set; }
    }
}
