//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfo
    {
        public int StockInfoId { get; set; }
        public Nullable<double> Sell { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> WorkerEditTime { get; set; }
    }
}
