//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.DailyPrices = new HashSet<DailyPrice>();
        }
    
        public int ArticleId { get; set; }
        public int LanguageId { get; set; }
        public bool isFoil { get; set; }
        public bool isSigned { get; set; }
        public bool isAltered { get; set; }
        public bool isPlayset { get; set; }
        public bool isFirstEd { get; set; }
        public Nullable<int> SiteWideCount { get; set; }
        public Nullable<System.DateTime> WorkerEditTime { get; set; }
        public int ProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyPrice> DailyPrices { get; set; }
        public virtual Product Product { get; set; }
        public virtual Language Language { get; set; }
    }
}
