//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPrice
    {
        public int DailyPriceId { get; set; }
        public Nullable<double> Sell { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<System.DateTime> WorkerEditTime { get; set; }
        public int Articleid { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
