//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagicManagerDataEntities : DbContext
    {
        public MagicManagerDataEntities()
            : base("name=MagicManagerDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<DailyPrice> DailyPrices { get; set; }
        public virtual DbSet<Expansion> Expansions { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<WorkerAction> WorkerActions { get; set; }
    }
}
