//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerAction
    {
        public int WorkerActionId { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
