//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicManager.DAL
{
    using Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MagicManagerEntities : DbContext
    {
        public MagicManagerEntities()
            : base("name=MagicManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<DailyPrice> DailyPrice { get; set; }
        public virtual DbSet<Expansion> Expansion { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<KeyValueModels> KeyValueModels { get; set; }
        public virtual DbSet<KeyValueTableModel> KeyValueTableModel { get; set; }
        public virtual DbSet<KeyValueTableModels> KeyValueTableModels { get; set; }
        public virtual DbSet<Lang> Lang { get; set; }
        public virtual DbSet<MarketInfo> MarketInfo { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<StockInfo> StockInfo { get; set; }
        public virtual DbSet<WorkerAction> WorkerAction { get; set; }
    }
}
